---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:oauth_token: 42982909-Ze1UFGtdoKXKlftDkM2VsuKVNwIvvX6YKQ6je8DP1
:oauth_secret: ql4bfBPTvXiW9Hl7oHc8os7l9baWWtWpEnavLJfrEts9s
